---
- name: インデックスファイルの存在確認
  ansible.builtin.stat:
    path: "{{ document_base_dir }}/index.md"
  register: document_index_result
- name: インデックスファイルを生成
  ansible.builtin.copy:
    src: files/mkdocs/index.md
    dest: "{{ document_base_dir }}/index.md"
    mode: "0644"
  when: document_index_result.stat.exists
- name: ナビゲーションファイルの存在確認
  ansible.builtin.stat:
    path: "{{ document_base_dir }}/SUMMARY.md"
  register: document_nav_result
- name: ナビゲーションファイルをコピー
  ansible.builtin.copy:
    src: files/mkdocs/SUMMARY.md
    dest: "{{ document_base_dir }}/SUMMARY.md"
    mode: "0644"
  when: document_nav_result.stat.exists
- name: カスタマイズ用CSSファイルの存在確認
  ansible.builtin.stat:
    path: "{{ document_asset_css_dir }}/extra.css"
  register: extra_css_result
- name: カスタマイズ用CSSファイルをコピー
  ansible.builtin.copy:
    src: files/mkdocs/extra.css
    dest: "{{ document_asset_css_dir }}/extra.css"
    mode: "0644"
  when: not extra_css_result.stat.exists
- name: カスタマイズ用JSファイルの存在確認
  ansible.builtin.stat:
    path: "{{ document_asset_js_dir }}/extra.js"
  register: extra_js_result
- name: カスタマイズ用CSSファイルをコピー
  ansible.builtin.copy:
    src: files/mkdocs/extra.js
    dest: "{{ document_asset_js_dir }}/extra.js"
    mode: "0644"
  when: not extra_js_result.stat.exists
